ICASTusa/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ICASTusa.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        // GET: About
        public ActionResult Who_We_Are()
        {
            return View();
        }

        public ActionResult History_of_ICAST()
        {
            return View();
        }

        public ActionResult The_ICAST_Team()
        {
            return View();
        }

        public ActionResult The_ICAST_Board()
        {
            return View();
        }

        public ActionResult ResourceSmart_Board(){
            return View();
        }

        public ActionResult ICAST_Partners()
        {
            return View();
        }
    }
}

ICASTusa/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ICASTusa.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ICAST_News()
        {
            return View();
        }

        public ActionResult ICAST_Events()
        {
            return View();
        }
    }
}

ICASTusa/Controllers/Get_InvolvedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ICASTusa.Controllers
{
    public class Get_InvolvedController : Controller
    {
        // GET: Get_Involved
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Jobs()
        {
            return View();
        }

        public ActionResult Volunteer()
        {
            return View();
        }

        public ActionResult Donate()
        {
            return View();
        }

        public ActionResult Connect_with_ICAST()
        {
            return View();
        }
    }
}

ICASTusa/Controllers/ProgramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ICASTusa.Controllers
{
    public class ProgramsController : Controller
    {
        // GET: Programs
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Green_Certifications()
        {
            return View();
        }

        public ActionResult Training_and_Resources()
        {
            return View();
        }
    }
}

ICASTusa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="fa fa-power-off fa-2x"></span>
                </button>
                <a href="@Url.Action("Index", "Home")"><img src="~/Content/Images/icast-header-logo.png"/></a>
            </div>
            <div class="navbar-collapse collapse" style="float: right">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "About")">About Us</a>
                        <ul class="dropdown">
                            <a href="@Url.Action("Who_We_Are", "About")"><li>Who We Are</li></a>
                            <a href="@Url.Action("History_of_ICAST", "About")"><li>Our History</li></a>
                            <a href="@Url.Action("The_ICAST_Team", "About")"><li>The ICAST Team</li></a>
                            <a href="@Url.Action("The_ICAST_Board", "About")"><li>ICAST Board of Directors</li></a>
                            <a href="@Url.Action("ResourceSmart_Board", "About")"><li>ResourceSmart Executive</li></a>
                            <a href="@Url.Action("ICAST_Partners", "About")"><li>Partners</li></a>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Programs</a>
                        <ul class="dropdown">
                            <a href="http://www.resourcesmart.org/" target="_blank"><li>ResourceSmart</li></a>
                            <a href="http://www.project-sunligh.org" target="_blank"><li>Project Sunlight</li></a>
                            <a href="http://www.tblfund.org" target="_blank"><li>TBL Fund</li></a>
                            <a href="@Url.Action("Green_Certifications", "Programs")"><li>Green Certifications</li></a>
                            <a href="@Url.Action("Training_and_Resources", "Programs")"><li>Training and Resources</li></a>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Success Stories</a>
                        <ul class="dropdown">
                            <a href="@Url.Action("Program_Success", "Success_Stories")"><li>Program Success</li></a>
                            <a href="@Url.Action("Case_Studies", "Success_Stories")"><li>Case Studies</li></a>
                            <a href="@Url.Action("Awards", "Success_Stories")"><li>Awards</li></a>
                            <a href="@Url.Action("Testimonials", "Success_Stories")"><li>Testimorials</li></a>
                        </ul>
                    </li>
                    <li>
                        <a href="#">The Latest</a>
                        <ul class="dropdown">
                            <a href="@Url.Action("ICAST_NEWS", "Blog")"><li>ICAST News</li></a>
                            <li><a href="@Url.Action("ICAST_Events", "BLog")">ICAST Events</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Get Involved</a>
                        <ul class="dropdown">
                            <a href="@Url.Action("Jobs", "Get_Involved")"><li>Jobs</li></a>
                            <a href="@Url.Action("Volunteer", "Get_Involved")"><li>Volunteer</li></a>
                            <a href="@Url.Action("Donate", "Get_Involved")"><li>Donate</li></a>
                            <a href="@Url.Action("Connect_with_ICAST", "Get_Involved")"><li>Connect with ICAST</li></a>
                        </ul>
                    </li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <!-- @Html.Partial("_LoginPartial") -->
            </div>
        </div>
    </div>
    <div class="container banner">
        <div class="row ">
            <div class="col-md-2" style="float: right; right: 300px">
                <br />
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Google Custom Search" />
                    <span class="input-group-btn">
                        <button class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="container" style="margin-top: 10px;">
        @RenderBody()
        <footer class="text-center">
            <a href="@Url.Action("Index", "Home")">HOME</a> |
            <a href="@Url.Action("ICAST_Events", "Blog")">CALENDAR</a> |
            <a href="@Url.Action("Connect_with_ICAST", "Get_Involved")">CONNECT WITH ICAST</a> |
            <a href="#">CONTACT ICAST INTERNATIONAL</a> |
            <a href="@Url.Action("Donate", "Get_Involved")">GET INVOLVED DONATE</a> |
            <a href="@Url.Action("Jobs", "Get_Involved")">GET INVOLVED JOBS</a> |
            <a href="@Url.Action("Volunteer", "Get_Involved")">GET INVOLVED VOLUNTEER</a> |
            <a href="@Url.Action("Green_Certifications", "Programs")">GREEN CERTIFICATIONS</a> |
            <a href="@Url.Action("History_of_ICAST", "About")">HISTORY OF ICAST INTERNATIONAL</a> |
            <a href="@Url.Action("ICAST_Partners", "About")">ICAST PARTNERS</a> |
            <a href="#">PROJECT SUNLIGHT</a> |
            <a href="#">PROMOTIONAL FORM</a> |
            <a href="@Url.Action("ResourceSmart_Board", "About")">RESOURCE SMART BOARD</a> |
            <a href="@Url.Action("Awards", "Success_Stories")">SUCCESS STORIES AWARDS</a> |
            <a href="@Url.Action("Case_Studies", "Success_Stories")">SUCCESS STORIES CASE STUDIES</a> |
            <a href="#">SUCCESS STORIES PAST PROJECTS</a> |
            <a href="@Url.Action("Testimonials", "Success_Stories")">SUCCESS STORIES TESTIMONIALS</a> |
            <a href="@Url.Action("The_ICAST_Board", "About")">THE ICAST BOARD</a> |
            <a href="@Url.Action("The_ICAST_Team", "About")">THE ICAST TEAM</a> |
            <a href="@Url.Action("Training_and_Resources", "Programs")">TRAINING AND RESOURCES</a> |
            <a href="@Url.Action("Who_We_Are", "About")">WHO WE ARE</a> |
            <a href="#">LOGIN</a>
            <p>&copy; @DateTime.Now.Year - ICAST All Rights Reserved <a href="">Site Map</a></p>
        </footer>
    </div>
    <div class="row bottomNav">
        <div class="navbar navbar-inverse navbar-fixed-bottom">
            <div class="container">
                <div class="col-md-4 text-left">
                    <ul class="nav navbar-nav">
                        <li><a href="#"><span class="glyphicon glyphicon-comment"></span> View Blog</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-calendar"></span> Events</a></li>
                    </ul>
                </div>
                <div class="col-md-4"></div>
                <div class="col-md-4 text-right">
                    <ul class="nav navbar-nav">
                        <li><a href="https://plus.google.com/110678628120966349089/about?hl=en"><span class="fa fa-google-plus-square fa-2x"></span></a></li>
                        <li><a href="https://www.facebook.com/icastusa"><span class="fa fa-facebook-square fa-2x"></span></a></li>
                        <li><a href="https://twitter.com/ICASTusa"><span class="fa fa-twitter-square fa-2x"></span></a></li>
                        <li><a href="https://www.linkedin.com/company/icast?trk=top_nav_home"><span class="fa fa-linkedin-square fa-2x"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>